# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: uLKIS

navbar-links:
  Home: ""
  Modules: "modules"
  About: "about"
#  Partner:
#    - ITS: "its"
#    - L3S: "l3s"
#    - Kinexon: "kinexon"

header_pages:
  - index.md
  - modules.md
  - about.md
  - board.md


# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: "/assets/img/mm4spa_full.svg"


email: maxklemp92@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  uLKIS is a BMBF-funded project, carried out at German Sport University Cologne, 
  aiming at creating Open Educational Resources for improving Data Science and Machine Learning skills among sports students.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  uLKIS

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
